# Define deployment targets.
# Required keys are deploy_dir and host.
# Optional keys are tag and ssh_port
demo:
    deploy_dir: "/services/apache/vhosts/demo.learn.extension.org/railsroot"
    host: "demo.learn.extension.org"
    ssh_port: 24 
