session_token: '123456789012345678901234567890'
urlwriter_host: 'learn.test'
app_location: 'localdev'
tropo_url: "http://api.tropo.com/1.0/sessions"
tropo_token: "notset"
send_notifications: false
default_feed_items: 50
max_feed_items: 200
minimum_recommendation_score: 1.0
recommended_events: 3
activity_notification_interval: 28800.0
rescheduled_notification_interval: 900.0
location_change_notification_interval: 900.0
engineering_list: 'engineering@extension.org'
default_display_timezone: 'Eastern Time (US & Canada)'
zoom_api_key: 'notset'
zoom_api_secret: 'notset'
zoom_webinar_id: 'notset'
zoom_webinar_host: 'extension.zoom.us'
mfln_registration_contacts: []
elasticsearch_prefix: 'localdev_learn'
elasticsearch_host_and_port: 'localhost:9200'
elasticsearch_enabled: false
